apiVersion: v1
kind: Ingress
metadata:
  name: pgadmin-ingress
  namespace: pgadmin 
spec:
  tls:
  - hosts:
    - pgadmin.bonoportifolio.com
    secretName: pgadmin-ingress-portal-tls
  rules:
  - host: pgadmin.bonoportifolio.com
    http:
      paths:
      - path:
        backend:
          serviceName: pgadmin-service
          servicePort: 80