prefix = "codebank"
cluster_name = "codebank-cluster"
aws_instance_types = ["t3.micro"]
retention_days = 30
desired_size = 2
max_size = 4
min_size = 2
vpc_cidr_block = "10.0.0.0/16"
terraform_state_bucket_name= "bono-terraform-tfstate-bucket"
terraform_state_bucket_key="codebank-terraform.tfstate"