variable "prefix" {}
variable "vpc_cidr_block" {}
variable "cluster_name" {}
variable retention_days {}
variable "desired_size" {}
variable "max_size" {}
variable "min_size" {}
variable "aws_instance_types" {}
variable "AWS_ACCESS_KEY_ID" {}
variable "AWS_SECRET_ACCESS_KEY" {}
variable "terraform_state_bucket_name" {}
variable "terraform_state_bucket_key" {}