apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: codebank-hpa
  namespace: codebank
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: codebank
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
