apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: invoices-frontend-hpa
  namespace: invoice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: invoices-frontend    
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
