apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: codebank-store-frontend-hpa
  namespace: store
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: codebank-store-frontend
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
