apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: store-api-hpa
  namespace: store
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: store-api
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
