name: identify_customer

on:
  issues:
    types:
      - opened
env:
  GITHUB_TOKEN: ${{ secrets.ORG_MEMBERSHIP_TOKEN }}
  MEMBER_LIST: ${{ secrets.CODEBANK_MEMBERS }}
  CREATOR: ${{ github.actor }}
  TITLE: ${{ github.event.issue.title }}
  NUMBER: ${{ github.event.issue.number }}
  TOKEN: ${{ secrets.CODEBANK_SLACK_BEARER_TOKEN }}
  REPO_URL: ${{ github.repository }}
  SLACK_HASHES: ${{ secrets.CODEBANK_GITHUB_SLACK_MAP }}

jobs:
  check-membership:
    runs-on: ubuntu-latest
    steps:
    - name: run script
      env:
          BOOL: ${{ contains( env.MEMBER_LIST, env.CREATOR ) }}
      if: ${{ env.BOOL == 'false' }}
      uses: CodeBank/github-action-identify-customer@main
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        env:
          BOOL: ${{ contains( env.MEMBER_LIST, env.CREATOR ) }}
        if: ${{ env.BOOL == 'false' }}
        uses: andymckay/labeler@1.0.3
        with:
          add-labels: "customer-submission"
