apiVersion: v1
kind: Service
metadata:
  annotations:
    ingress.kubernetes.io/service-upstream : "true"
  labels:
    app: invoices-api
    version: v1
    stack: echo
    interface: rest
    language: nestjs
  name: invoices-api
  namespace: invoice
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: invoices-api
