apiVersion: v1
kind: Service
metadata:
  annotations:
    ingress.kubernetes.io/service-upstream : "true"
  labels:
    app: codebank-store-frontend
    version: v1
    stack: echo
    interface: webapp
    language: nextjs
  name: codebank-store-frontend
  namespace: store
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: codebank-store-frontend
