#!/bin/bash

git clone git@github.com:CodeBank/accountant-aws-marketplace.git
git clone git@github.com:CodeBank/ansible-playbook-demo.git
git clone git@github.com:CodeBank/ansible-role-senzingapi.git
git clone git@github.com:CodeBank/ansible-role-stream-producer.git
git clone git@github.com:CodeBank/awesome.git
git clone git@github.com:CodeBank/aws-cloudformation-database-cluster.git
git clone git@github.com:CodeBank/aws-cloudformation-dev-rest.git
git clone git@github.com:CodeBank/aws-cloudformation-ecs.git
git clone git@github.com:CodeBank/aws-cloudformation-ecs-poc-simple.git
git clone git@github.com:CodeBank/aws-cloudformation-ecs-senzing-stack-basic.git
git clone git@github.com:CodeBank/aws-cloudformation-ecs-senzing-stack-choices.git
git clone git@github.com:CodeBank/aws-lambda-cognito-authorizer.git
git clone git@github.com:CodeBank/aws-lambda-self-signed-certificate.git
git clone git@github.com:CodeBank/aws-marketplace-evaluation.git
git clone git@github.com:CodeBank/azure-template-aks-poc-simple.git
git clone git@github.com:CodeBank/certification.git
git clone git@github.com:CodeBank/certified.git
git clone git@github.com:CodeBank/charts.git
git clone git@github.com:CodeBank/community-map.git
git clone git@github.com:CodeBank/community-roadmap.git
git clone git@github.com:CodeBank/compressedfile.git
git clone git@github.com:CodeBank/configurator.git
git clone git@github.com:CodeBank/connector-neo4j.git
git clone git@github.com:CodeBank/data-encryption-aes256cbc-sample.git
git clone git@github.com:CodeBank/data-mart-replicator.git
git clone git@github.com:CodeBank/docker-adminer.git
git clone git@github.com:CodeBank/docker-app-demo.git
git clone git@github.com:CodeBank/docker-apt.git
git clone git@github.com:CodeBank/docker-aptdownloader.git
git clone git@github.com:CodeBank/docker-base-image-centos.git
git clone git@github.com:CodeBank/docker-base-image-debian.git
git clone git@github.com:CodeBank/docker-compose-air-gapper.git
git clone git@github.com:CodeBank/docker-compose-aws-ecscli-demo.git
git clone git@github.com:CodeBank/docker-compose-db2-cluster-demo.git
git clone git@github.com:CodeBank/docker-compose-db2-demo.git
git clone git@github.com:CodeBank/docker-compose-demo.git
git clone git@github.com:CodeBank/docker-compose-mysql-demo.git
git clone git@github.com:CodeBank/docker-compose-postgresql-demo.git
git clone git@github.com:CodeBank/docker-compose-stream-loader-kafka-demo.git
git clone git@github.com:CodeBank/docker-db2.git
git clone git@github.com:CodeBank/docker-db2-driver-installer.git
git clone git@github.com:CodeBank/docker-db2express-c.git
git clone git@github.com:CodeBank/docker-g2command.git
git clone git@github.com:CodeBank/docker-g2command-db2-cluster.git
git clone git@github.com:CodeBank/docker-g2configtool.git
git clone git@github.com:CodeBank/docker-g2loader.git
git clone git@github.com:CodeBank/docker-g2loader-db2-cluster.git
git clone git@github.com:CodeBank/docker-hello-world.git
git clone git@github.com:CodeBank/docker-ibm-db2.git
git clone git@github.com:CodeBank/docker-init-container.git
git clone git@github.com:CodeBank/docker-installer.git
git clone git@github.com:CodeBank/docker-jupyter.git
git clone git@github.com:CodeBank/docker-mysql.git
git clone git@github.com:CodeBank/docker-mysql-init.git
git clone git@github.com:CodeBank/docker-opt-senzing.git
git clone git@github.com:CodeBank/docker-poc-notebook.git
git clone git@github.com:CodeBank/docker-python-3.6-base.git
git clone git@github.com:CodeBank/docker-python-base-complete.git
git clone git@github.com:CodeBank/docker-python-db2-base.git
git clone git@github.com:CodeBank/docker-python-db2-cluster-base.git
git clone git@github.com:CodeBank/docker-python-db2-cluster-demo.git
git clone git@github.com:CodeBank/docker-python-demo.git
git clone git@github.com:CodeBank/docker-python-mysql-base.git
git clone git@github.com:CodeBank/docker-python-postgresql-base.git
git clone git@github.com:CodeBank/docker-senzing-base.git
git clone git@github.com:CodeBank/docker-senzing-console.git
git clone git@github.com:CodeBank/docker-senzing-debug.git
git clone git@github.com:CodeBank/docker-sshd.git
git clone git@github.com:CodeBank/docker-terraform-aws.git
git clone git@github.com:CodeBank/docker-test.git
git clone git@github.com:CodeBank/docker-test-layers.git
git clone git@github.com:CodeBank/docker-web-app-demo.git
git clone git@github.com:CodeBank/docker-wrap-image-with-senzing-apt.git
git clone git@github.com:CodeBank/docker-wrap-image-with-senzing-data.git
git clone git@github.com:CodeBank/docker-xterm.git
git clone git@github.com:CodeBank/docker-yum.git
git clone git@github.com:CodeBank/docker-yumdownloader.git
git clone git@github.com:CodeBank/dockerhub-util.git
git clone git@github.com:CodeBank/dumpstack.git
git clone git@github.com:CodeBank/elasticsearch.git
git clone git@github.com:CodeBank/entity-search-web-app.git
git clone git@github.com:CodeBank/entity-search-web-app-console.git
git clone git@github.com:CodeBank/evaluate.git
git clone git@github.com:CodeBank/g2-configuration-initializer.git
git clone git@github.com:CodeBank/g2-python.git
git clone git@github.com:CodeBank/g2-sdk-java.git
git clone git@github.com:CodeBank/g2-sdk-python.git
git clone git@github.com:CodeBank/g2anon.git
git clone git@github.com:CodeBank/g2audit.git
git clone git@github.com:CodeBank/g2command.git
git clone git@github.com:CodeBank/g2config.git
git clone git@github.com:CodeBank/g2configmgr.git
git clone git@github.com:CodeBank/g2configtables.git
git clone git@github.com:CodeBank/g2configtool.git
git clone git@github.com:CodeBank/g2createinstance.git
git clone git@github.com:CodeBank/g2createproject.git
git clone git@github.com:CodeBank/g2database.git
git clone git@github.com:CodeBank/g2diagnostic.git
git clone git@github.com:CodeBank/g2engine.git
git clone git@github.com:CodeBank/g2exception.git
git clone git@github.com:CodeBank/g2explorer.git
git clone git@github.com:CodeBank/g2export.git
git clone git@github.com:CodeBank/g2hasher.git
git clone git@github.com:CodeBank/g2health.git
git clone git@github.com:CodeBank/g2iniparams.git
git clone git@github.com:CodeBank/g2loader.git
git clone git@github.com:CodeBank/g2module.git
git clone git@github.com:CodeBank/g2paths.git
git clone git@github.com:CodeBank/g2product.git
git clone git@github.com:CodeBank/g2project.git
git clone git@github.com:CodeBank/g2replicator.git
git clone git@github.com:CodeBank/g2report.git
git clone git@github.com:CodeBank/g2s3.git
git clone git@github.com:CodeBank/g2search.git
git clone git@github.com:CodeBank/g2service.git
git clone git@github.com:CodeBank/g2setupconfig.git
git clone git@github.com:CodeBank/g2snapshot.git
git clone git@github.com:CodeBank/g2updateproject.git
git clone git@github.com:CodeBank/g2vcompare.git
git clone git@github.com:CodeBank/github-action-add-issue-to-project.git
git clone git@github.com:CodeBank/github-action-identify-customer.git
git clone git@github.com:CodeBank/github-util.git
git clone git@github.com:CodeBank/governor-postgresql-transaction-id.git
git clone git@github.com:CodeBank/hello-senzing-springboot-java.git
git clone git@github.com:CodeBank/i2-senzing-connector.git
git clone git@github.com:CodeBank/ibm-icp4d-guide.git
git clone git@github.com:CodeBank/ibm-openshift-guide.git
git clone git@github.com:CodeBank/images.git
git clone git@github.com:CodeBank/java-g2loader.git
git clone git@github.com:CodeBank/knowledge-base.git
git clone git@github.com:CodeBank/kubernetes-demo.git
git clone git@github.com:CodeBank/mapper-base.git
git clone git@github.com:CodeBank/mapper-csv.git
git clone git@github.com:CodeBank/mapper-dnb.git
git clone git@github.com:CodeBank/mapper-dowjones.git
git clone git@github.com:CodeBank/mapper-icij.git
git clone git@github.com:CodeBank/mapper-leie.git
git clone git@github.com:CodeBank/mapper-nomino.git
git clone git@github.com:CodeBank/mapper-npi.git
git clone git@github.com:CodeBank/mapper-ofac.git
git clone git@github.com:CodeBank/mapper-openc.git
git clone git@github.com:CodeBank/mapper-opensanctions.git
git clone git@github.com:CodeBank/mapper-sayari.git
git clone git@github.com:CodeBank/migrate.git
git clone git@github.com:CodeBank/mock-data-generator.git
git clone git@github.com:CodeBank/openshift-demo.git
git clone git@github.com:CodeBank/packer-ansible.git
git clone git@github.com:CodeBank/packer-senzing-demo-ubuntu-18.04.git
git clone git@github.com:CodeBank/postgresql-client.git
git clone git@github.com:CodeBank/postgresql-performance.git
git clone git@github.com:CodeBank/rabbitmq-performance.git
git clone git@github.com:CodeBank/rancher-demo.git
git clone git@github.com:CodeBank/ready-for-senzing.git
git clone git@github.com:CodeBank/redoer.git
git clone git@github.com:CodeBank/resolver.git
git clone git@github.com:CodeBank/rest-api-client-java.git
git clone git@github.com:CodeBank/rest-api-client-ng.git
git clone git@github.com:CodeBank/risk-score-calculator.git
git clone git@github.com:CodeBank/sdk-components-ng.git
git clone git@github.com:CodeBank/sdk-graph-components.git
git clone git@github.com:CodeBank/senzing-api-server.git
git clone git@github.com:CodeBank/senzing-commons-java.git
git clone git@github.com:CodeBank/senzing-data-encryption-specification.git
git clone git@github.com:CodeBank/senzing-entity-specification.git
git clone git@github.com:CodeBank/senzing-environment.git
git clone git@github.com:CodeBank/senzing-listener.git
git clone git@github.com:CodeBank/senzing-package.git
git clone git@github.com:CodeBank/senzing-poc-server.git
git clone git@github.com:CodeBank/senzing-rest-api-specification.git
git clone git@github.com:CodeBank/senzing-sdk-api-specification.git
git clone git@github.com:CodeBank/senzing-up.git
git clone git@github.com:CodeBank/senzing.github.io.git
git clone git@github.com:CodeBank/senzinggo.git
git clone git@github.com:CodeBank/spike-docker-store-based-images.git
git clone git@github.com:CodeBank/stream-configuration.git
git clone git@github.com:CodeBank/stream-file-utility.git
git clone git@github.com:CodeBank/stream-loader.git
git clone git@github.com:CodeBank/stream-logger.git
git clone git@github.com:CodeBank/stream-producer.git
git clone git@github.com:CodeBank/subway-map.git
git clone git@github.com:CodeBank/support.git
git clone git@github.com:CodeBank/template-ansible-role.git
git clone git@github.com:CodeBank/template-docker.git
git clone git@github.com:CodeBank/template-python.git
git clone git@github.com:CodeBank/template-repository.git
git clone git@github.com:CodeBank/test-ground.git
git clone git@github.com:CodeBank/truth-sets.git
git clone git@github.com:CodeBank/video.git
git clone git@github.com:CodeBank/webapp-drillthrough-demo.git
