name: "7 - Terraform Destroy Infra"
on:
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
          DOCKER_REPOSITORY: richiebono
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TERRAFORM_VERSION: 1.2.6
          WORKING_DIRECTORY: terraform

        defaults:
          run:
            shell: bash
            working-directory: ${{ env.WORKING_DIRECTORY }}

        steps:
          - name: Checkout Code
            uses: actions/checkout@v2

          - name: Install Terraform
            uses: hashicorp/setup-terraform@v1
            with:
                terraform_version: ${{ env.TERRAFORM_VERSION }}

          - name: Terraform Init
            id: init           
            run: terraform init
              
          - name: Terraform Format
            id: format
            run: terraform fmt -check
            continue-on-error: true

          - name: Terraform Plan
            id: plan            
            run: terraform plan -no-color 

          - name: Terraform Apply Destroy       
            id: destroy  
            run: terraform destroy -auto-approve